#Edit the registries in a ConfigMap resource, which will get mounted to the pod running Argo CD Image Updater.
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: jfrog Container Registry
      api_url: https://sn1-r620-a04-03.puretec.purestorage.com
      prefix: sn1-r620-a04-03.puretec.purestorage.com
      ping: no
      credentials: secret:argocd/jfrog-cred#cred
  