apiVersion: v1
kind: Secret
metadata:
  name: XX_SECRET_NAME_XX
  namespace: XX_NAMESPACE_FOR_BACKUP_CRD_XX
  annotations:
    stork.libopenstorage.org/skipresource: "true"
stringData:
  region: XX_REGION_XX
  accessKeyID: XX_ACCESS_KEYID_XX
  secretAccessKey: XX_SECRET_ACCESS_KEY_XX
  endpoint: "XX_BUCKET_ENDPOINT_XX"
  disableSSL: "XX_DISABLE_SSL_XX"
  encryptionKey: "atestKey"

---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
  name: XX_BACKUP_LOCATION_NAME_XX
  namespace: XX_NAMESPACE_FOR_BACKUP_CRD_XX
  annotations:
    stork.libopenstorage.org/skipresource: "true"
location:
  type: s3
  path: "XX_BUCKET_NAME_XX"
  secretConfig: XX_SECRET_NAME_XX
  sync: true

