apiVersion: v1
kind: Service
metadata:
  name: git-server-service
  namespace: XX-namespace-XX
  labels:
    type: git-server
  labels:
    type: git-server        
spec:
  selector:
    type: git-server
  type: LoadBalancer
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
