---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationRestore
metadata:
  name: XX_APPLICATION_RESTORE_NAME_XX
  namespace: XX_NAMESPACE_FOR_BACKUP_CRD_XX
spec:
  backupName: XX_APPLICATION_BACKUP_NAME_XX
  backupLocation: XX_BACKUP_LOCATION_NAME_XX
  namespaceMapping:
    XX_SOURCE_NAMESPACE_XX: XX_DESTINATION_NAMESPACE_XX
  replacePolicy: Delete
