apiVersion: stork.libopenstorage.org/v1alpha1
kind: VolumeSnapshotRestore
metadata:
  name: wordpress-app-restore-XX-restorename-XX
  namespace: wordpress-main
  labels:
    name: restore-of-wordpress-app
spec:
  sourceName: XX-snapshot-name-XX
  sourceNamespace: wordpress-main
