apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: ci-for-wordpress-app-dev-branch
  namespace: argo
spec:
  entryPoint: ci-pipeline-to-automate-build-and-namespace-backup
  volumes:
  - name: jfrog-config
    secret:
      secretName: jfrog-config
      items:
        - key: .dockerconfigjson
          path: config.json                 
  - name: application-build-code
  - name: application-dockefile
  - name: kubeconfig
    secret:
      secretName: kubernetes-kube-config  
  - name: repo-sshkey
    secret:
      secretName: wordpress-repo-sshkey    
  - name: snapshot
    secret:
      secretName: wordpress-snapshot-script
  - name: restorescript
    secret:
      secretName: wordpress-restore-snapshot-script           
  templates:
  - name: ci-pipeline-to-automate-build-and-namespace-backup
    dag:
      tasks:            
      - name: on-fail
        template: dind-sidecar-example        
  - name: dind-sidecar-example
    container:
      image: ubuntu         # Docker already provides an image for running a Docker daemon
      command: ["/bin/sh", "-c"]
      args: 
      - |
        apt update
        apt install curl git docker-compose -y 
        curl https://releases.rancher.com/install-docker/20.10.sh | sh
        /etc/init.d/docker start
        useradd wordpress -s /bin/bash
        usermod -a -G docker wordpress
        curl -fsSL https://deb.nodesource.com/setup_12.x | bash
        apt-get install -y nodejs        
        su - wordpress -c "git clone https://github.com/WordPress/wordpress-develop.git && cd wordpress-develop && rm package.json && rm -rf tests/phpunit/tests/* && mv src src-bak && mkdir src && cp -r src-bak/js src && ls -lrth  tests/phpunit/tests/"
        su - wordpress -c "git clone https://gitlab.redblink.net/nishit/phpunit.git && cp -r phpunit/code/* wordpress-develop/src && ls -lrth wordpress-develop/src && cp phpunit/package.json wordpress-develop/ && cp -r phpunit/test-cases/* wordpress-develop/tests/phpunit/tests/"
        ls -lrth /home/wordpress/wordpress-develop/tests/phpunit/tests/
        su - wordpress -c "cd wordpress-develop && npm install && npm run build:dev && npm run env:start && 
        echo '             ' && docker ps && sleep 10 &&  npm run env:install && sleep 10 && npm run test:php"        
      securityContext:
        privileged: true  
      volumeMounts:
      - name: application-build-code
        mountPath: /home/wordpress   
      - name: application-dockefile
        mountPath: /var/lib/docker                     