apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-XX-appName-XX-app-dev-branch
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: XX-branch-name-XX
      eventSourceName: XX-webhookName-XX-webhook
      eventName: XX-branch-name-XX
  triggers:
  - template:
      name: ci-pipeline
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:          
              generateName: ci-XX-appName-XX-app-dev-
              namespace: argo
            spec:
              workflowTemplateRef:
                name: XX-Workflow-template-dev-branch-XX
                clusterScope: true