
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: code-manifest
  name: git-repo-code-main
  labels:
    app: git-server-for-application-manifest
    include-in-backup: yes
spec:
  storageClassName: px-gitrepo-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
