
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: git-mac3
  name: git-repo-git-mac3
  labels:
    app: git-server-for-git-mac3
    include-in-backup: yes
    type: git-server
spec:
  storageClassName: px-gitrepo-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
