
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: git-mac3
  name: git-server-for-git-mac3
spec:
  template:
    spec:
      schedulerName: stork
      containers:
        - name: git-server-for-git-mac3
          volumeMounts:
          - mountPath: /home/git/repos/git-mac3
            name: git-repo-git-mac3
      volumes:
      - name: git-repo-git-mac3
        persistentVolumeClaim:
          claimName: git-repo-git-mac3
