apiVersion: stork.libopenstorage.org/v1alpha1
kind: VolumeSnapshotRestore
metadata:
  name: java-app-restore-XX-restorename-XX
  namespace: springboot-dev
  labels:
    name: restore-of-java-app
spec:
  sourceName: XX-snapshot-name-XX
  sourceNamespace: springboot-dev
