apiVersion: v1
kind: Service
metadata:
  name: git-server-service
  namespace: XX-namespace-XX
  labels:
    app: git-server-for-XX-label-XX
spec:
  selector:
    app: git-server-for-XX-label-XX
  type: LoadBalancer
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: XX-namespace-XX
  name: git-server-for-XX-label-XX
  labels:
    app: git-server-for-XX-label-XX
    include-in-backup: yes
    type: git-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: git-server-for-XX-label-XX
      include-in-backup: yes
      type: git-server
# strategy:
#   type: Recreate
  template:
    metadata:
      labels:
        app: git-server-for-XX-label-XX
        include-in-backup: yes
        type: git-server
    spec:
      imagePullSecrets:
      - name: regcred    
      schedulerName: stork
      containers:
      - name: git-server-for-XX-label-XX
        image: bikashrc25/git-server:latest
        ports:
        - containerPort: 22
        lifecycle:
          postStart:
            exec:
               command: ['/bin/sh', '-c', 'bash /root/deploy.sh']    
        volumeMounts:
        - name: ssh-key
          mountPath: /root/.ssh 
        - name: deployment
          mountPath: /root                        
      volumes:
      - name: ssh-key
        secret:
          secretName: git-ssh-key
      - name: deployment
        secret:
          secretName: deployment                
