#!/bin/bash

echo "determining branch"

if ! [ -t 0 ]; then
  read -a ref
fi

IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ "master" == "$branch" ]; then
  Commit="build:"
  LatestCommit="$(git log -1 --stat | awk 'FNR==5{print $1}')"
  if [ "$Commit" == "$LatestCommit" ]; then
  echo "new build"
  else
  echo 'master was pushed'
  curl -d '{"message":"ci pipeline"}' -H "Content-Type: application/json" -X POST 10.21.152.146:13000/master
  fi  
fi
